target = "template_release"
debug_symbols = "no"
optimize = "size"
lto = "full"
disable_3d = "yes"
module_text_server_adv_enabled = "no"
module_text_server_fb_enabled = "yes"
deprecated = "no"  # Disables deprecated features
vulkan = "no"  # Disables the Vulkan driver (used in Forward+/Mobile Renderers)
use_volk = "no"  # Disables more Vulkan stuff
openxr = "no"  # Disables Virtual Reality/Augmented Reality stuff
minizip = "no"  # Disables ZIP archive support
modules_enabled_by_default = "no"
module_gdscript_enabled = "yes"
module_text_server_fb_enabled = "yes"
module_freetype_enabled = "yes"
module_svg_enabled = "yes"
module_webp_enabled = "yes"
module_godot_physics_2d_enabled = "yes"
