name: Dev build

on: 
  push:
    branches: '**'
  pull_request:

env:
  GODOT_VERSION: 4.7.1
  EXPORT_NAME: Easel
  TAG: beta

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-24.04
    container:
      image: docker://barichello/godot-ci:${GODOT_VERSION}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true
        
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Import resources once
        continue-on-error: true
        run: godot --headless -v --import

      - name: Windows Build
        run: |
          godot --headless -v --export-release "Windows Desktop 64-bit" ./build/${EXPORT_NAME}-Windows-64bit/${EXPORT_NAME}.exe
          godot --headless -v --export-release "Windows Desktop arm64" ./build/${EXPORT_NAME}-Windows-arm64/${EXPORT_NAME}.exe

      - name: Copy easel_app_data folder
        run: |
          rm ./gesture_app_data/.gdignore
          cp -R ./easel_app_data ./build/${EXPORT_NAME}-Windows-64bit
          cp -R ./easel_app_data ./build/${EXPORT_NAME}-Windows-arm64
          cp -R ./easel_app_data ./build

      - name: Zip
        working-directory: ./build
        run: |
          zip -r ${EXPORT_NAME}-Windows-64bit.zip ${EXPORT_NAME}-Windows-64bit
          zip -r ${EXPORT_NAME}-Windows-arm64.zip ${EXPORT_NAME}-Windows-arm64

      - name: Build installer
        run: |
          apt-get update && apt-get install -y python3 && apt-get install -y nsis
          python3 ./installer/utils/po2nsi.py -i ./installer/easel-app.nsi -o ./installer/easel-app_loc.nsi -p ./installer/po -l "English" -v
          makensis ./installer/easel-app_loc.nsi
          mkdir ./build/installer
          mv ./installer/${EXPORT_NAME}_${TAG}_setup.exe ./build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows_build
          path: |
            ./build/
            !./build/*.zip

  export-linux:
    name: Linux Export
    runs-on: ubuntu-24.04
    container:
      image: docker://barichello/godot-ci:${GODOT_VERSION}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Import resources once
        continue-on-error: true
        run: godot --headless -v --import

      - name: Linux Build
        run: |
          godot --headless -v --export-release "Linux 64-bit" ./build/${EXPORT_NAME}-Linux-64bit/${EXPORT_NAME}.x86_64
          godot --headless -v --export-release "Linux arm64" ./build/${EXPORT_NAME}-Linux-arm64/${EXPORT_NAME}.arm64

      - name: Give execute permission
        run: |
          chmod +x ./build/${EXPORT_NAME}-Linux-64bit/${EXPORT_NAME}.x86_64
          chmod +x ./build/${EXPORT_NAME}-Linux-arm64/${EXPORT_NAME}.arm64

      - name: Copy easel_app_data folder
        run: |
          rm ./easel_app_data/.gdignore
          cp -R ./easel_app_data ./build/${EXPORT_NAME}-Linux-64bit
          cp -R ./easel_app_data ./build/${EXPORT_NAME}-Linux-arm64

      - name: Create tar.gz archive
        run: |
          cd build
          tar zcvf ${EXPORT_NAME}-Linux-64bit.tar.gz ${EXPORT_NAME}-Linux-64bit
          tar zcvf ${EXPORT_NAME}-Linux-arm64.tar.gz ${EXPORT_NAME}-Linux-arm64

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux_build
          path: |
            ./build/*.tar.gz

  export-mac:
    name: Mac Export
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Setup environment
        run: |
          export GODOT_VERSION=${GODOT_VERSION}
          export EXPORT_NAME=${EXPORT_NAME}

      - name: Download and extract export templates
        run: |
          mkdir -v -p "/Users/runner/Library/Application Support/Godot/export_templates/${GODOT_VERSION}.stable"
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          unzip -a Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          mv ./templates/* "/Users/runner/Library/Application Support/Godot/export_templates/${GODOT_VERSION}.stable"

      - name: Download Godot headless binary
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_macos.universal.zip
          unzip -a Godot_v${GODOT_VERSION}-stable_macos.universal.zip

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Import resources once
        continue-on-error: true
        run: ./Godot.app/Contents/MacOS/Godot --headless -v --import

      - name: Mac Build 🔧
        run: |
          chown runner ./Godot.app/Contents/MacOS/Godot
          chmod +x ./Godot.app/Contents/MacOS/Godot
          ./Godot.app/Contents/MacOS/Godot --headless -v --export-release "macOS" ./build/${EXPORT_NAME}.zip

      - name: Make application executable 🔧
        run: |
          unzip -a ./build/${EXPORT_NAME}.zip -d ./build
          chmod +x ./build/${EXPORT_NAME}.app/Contents/MacOS/${EXPORT_NAME}
          rm ./build/${EXPORT_NAME}.zip

      - name: Fix application icon 🖼
        run: sips -s format icns ./build/mac/${EXPORT_NAME}.app/Contents/Resources/icon.icns --out ./build/mac/${EXPORT_NAME}.app/Contents/Resources/icon.icns

      - name: Copy easel_app_data folder
        run: |
          cp -R ./easel_app_data ./build/${EXPORT_NAME}.app/Contents/Resources
          rm ./build/${EXPORT_NAME}.app/Contents/Resources/easel_app_data/.gdignore

      - name: Ad-hoc signing
        run: codesign -s - --force --deep ./build/${EXPORT_NAME}.app

      - name: Create DMG archive 🔧
        run: hdiutil create -srcfolder ./build/mac -fs HFS+ -volname ${EXPORT_NAME} ./build/mac/${EXPORT_NAME}-Mac.dmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac_build
          path: |
            ./build/*
  
  export-android:
    name: Android Export
    runs-on: ubuntu-24.04
    container:
      image: docker://barichello/godot-ci:${GODOT_VERSION}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Import resources once
        continue-on-error: true
        run: godot --headless -v --import

      - name: Android Build
        run: |
          godot --headless -v --export-release "Android" ./build/${EXPORT_NAME}-Android/${EXPORT_NAME}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: android_build
          path: |
            ./build/*